// Curiosidade/data comemorativa do dia, exibida na tela de Métricas
// Executivas abaixo do calendário (pedido do usuário, 2026-09-18). Lista
// curada manualmente (365 entradas, uma por dia do ano, chave 'M-D' sem
// zero à esquerda) em vez de API pública de datas comemorativas — decisão
// registrada na conversa: controle de qualidade e curadoria de relevância
// pro negócio (comida/bebida/consumo) importam mais aqui do que cobertura
// automática, e uma API externa é mais um ponto de falha sem necessidade.
// Quando o dia tem mais de um evento (múltiplas frases na fonte original,
// separadas por " / "), mostra só o primeiro, pra manter o texto curto e
// discreto. Dias sem evento cadastrado na fonte original (marcados como
// "(sem data especial registrada)") ficam de fora do objeto — o dashboard
// simplesmente não mostra a linha nesses dias.
const DATAS_COMEMORATIVAS = {
  "1-1":"Confraternização Universal",
  "1-2":"Dia Mundial dos Introvertidos",
  "1-3":"Dia do Juiz de Menores",
  "1-4":"Dia da Abreugrafia",
  "1-5":"Criação da 1ª Tipografia no Brasil",
  "1-6":"Dia da Gratidão",
  "1-7":"Dia da Liberdade de Cultos",
  "1-8":"Dia do Fotógrafo",
  "1-9":"Dia do Astronauta",
  "1-10":"Festa de São Gonçalo do Amarante",
  "1-11":"Dia do Controle da Poluição por Agrotóxicos",
  "1-12":"Dia do Empresário Contábil",
  "1-13":"Dia Internacional do Leonismo",
  "1-14":"Dia Internacional da Pipa",
  "1-15":"Dia dos Adultos",
  "1-16":"Dia dos Cortadores de Cana-de-açúcar",
  "1-17":"Dia dos Tribunais de Contas do Brasil",
  "1-18":"Dia de Santo Irmão Jaime Hilário",
  "1-19":"Dia Internacional do Queijo Quark",
  "1-20":"Dia do Farmacêutico",
  "1-21":"Dia Internacional do Moletom",
  "1-22":"Dia de Santo André",
  "1-23":"Dia Internacional da Medicina Integrativa",
  "1-24":"Dia Internacional da Educação",
  "1-25":"Dia do Carteiro",
  "1-26":"Dia da Gula",
  "1-27":"Dia Internacional em Memória às Vítimas do Holocausto",
  "1-28":"Dia Internacional da Privacidade de Dados",
  "1-29":"Dia Internacional do Hanseniano",
  "1-30":"Dia da Saudade",
  "1-31":"Dia do Lançamento do 1º Satélite (EUA)",
  "2-1":"Dia do Publicitário",
  "2-2":"Dia de Iemanjá",
  "2-3":"Dia da Navegação no Rio São Francisco",
  "2-4":"Criação do Facebook (2004)",
  "2-5":"Dia do Datiloscopista",
  "2-6":"Dia Internacional da Tolerância Zero à Mutilação Vaginal",
  "2-7":"Dia do Gráfico",
  "2-8":"Dia do Quadro do Magistério do Exército",
  "2-10":"Dia Mundial das Leguminosas",
  "2-11":"Dia Internacional das Mulheres e Meninas na Ciência",
  "2-12":"Dia de Darwin",
  "2-13":"Dia Mundial do Rádio",
  "2-14":"Dia Internacional da Doação de Livros",
  "2-15":"Dia Internacional de Luta contra o Câncer na Infância",
  "2-16":"Dia do Repórter",
  "2-17":"Carnaval",
  "2-18":"Quarta-feira de Cinzas",
  "2-19":"Dia do Esportista",
  "2-20":"Dia Mundial da Justiça Social",
  "2-21":"Dia Internacional da Baleia",
  "2-22":"Dia do Auxiliar de Serviços Gerais",
  "2-23":"Dia do Rotaryano",
  "2-24":"Promulgação da 1ª Constituição Republicana (1891)",
  "2-25":"Dia da Criação do Ministério das Comunicações",
  "2-26":"Dia do Comediante",
  "2-27":"Dia do Agente Fiscal da Receita Federal",
  "2-28":"Dia da Ressaca",
  "3-1":"Dia da Discriminação Zero",
  "3-2":"Dia da Oração",
  "3-3":"Dia Mundial da Vida Selvagem",
  "3-4":"Dia Mundial da Oração",
  "3-5":"Dia do Filatelista Brasileiro",
  "3-6":"Dia Internacional do Optometrista",
  "3-7":"Dia dos Fuzileiros Navais",
  "3-8":"Dia Internacional da Mulher",
  "3-9":"Dia Internacional do DJ",
  "3-10":"Dia Internacional da Gaita de Foles",
  "3-11":"Dia Internacional do Encanamento",
  "3-12":"Dia Internacional da Pochete",
  "3-13":"Dia do Conservacionismo",
  "3-14":"Dia do Vendedor de Livros",
  "3-15":"Dia Mundial do Consumidor",
  "3-16":"Dia Nacional de Conscientização sobre as Mudanças Climáticas",
  "3-18":"Dia Nacional da Imigração Judaica",
  "3-19":"Dia de São José",
  "3-20":"Dia Internacional da Felicidade",
  "3-21":"Dia Mundial da Poesia",
  "3-22":"Dia Mundial da Água",
  "3-23":"Dia Mundial da Meteorologia",
  "3-24":"Dia Mundial da Tuberculose",
  "3-25":"Dia Nacional do Oficial de Justiça",
  "3-26":"Dia do Cacau",
  "3-27":"Dia do Circo",
  "3-28":"Dia do Diagramador",
  "3-29":"1º voo de balão dirigível no Rio (1882)",
  "3-30":"Dia Mundial da Juventude",
  "3-31":"Dia da Integração Nacional",
  "4-1":"Dia da Mentira",
  "4-2":"Dia do Propagandista",
  "4-3":"Dia do Atuário",
  "4-4":"Dia Nacional do Parkinsoniano",
  "4-5":"Dia das Telecomunicações",
  "4-6":"Dia Nacional de Mobilização pela Saúde e Qualidade de Vida",
  "4-7":"Dia do Corretor",
  "4-8":"Dia da Natação",
  "4-9":"Dia Nacional do Aço",
  "4-10":"Dia da Engenharia",
  "4-11":"Dia do Infectologista",
  "4-12":"Dia do Obstetra",
  "4-13":"1ª Execução do Hino Nacional (1831)",
  "4-14":"Dia Pan-Americano",
  "4-15":"Dia da Conservação do Solo",
  "4-16":"Dia da Voz",
  "4-17":"Dia do Lojista de CD",
  "4-18":"Dia de Monteiro Lobato",
  "4-19":"Dia do Exército Brasileiro",
  "4-20":"Dia do Diplomata",
  "4-21":"Tiradentes",
  "4-22":"Descobrimento do Brasil (1500)",
  "4-23":"Dia de São Jorge",
  "4-24":"Dia do Agente de Viagem",
  "4-25":"Dia Mundial da Malária",
  "4-26":"Dia Mundial da Propriedade Intelectual",
  "4-27":"Dia da Empregada Doméstica",
  "4-28":"Dia Mundial da Segurança e Saúde no Trabalho",
  "4-29":"Dia Internacional da Dança",
  "4-30":"Dia Internacional do Jazz",
  "5-1":"Dia Mundial do Trabalho",
  "5-2":"Dia Mundial do Atum",
  "5-3":"Dia Mundial da Liberdade de Imprensa",
  "5-4":"Dia do Calculista Estrutural",
  "5-5":"Dia do Artista Pintor",
  "5-6":"Dia do Cartógrafo",
  "5-7":"Dia do Oftalmologista",
  "5-8":"Dia do Profissional de Marketing",
  "5-9":"Dia da Europa",
  "5-10":"Dia das Mães",
  "5-11":"Dia Mundial das Aves Migratórias",
  "5-12":"Dia Mundial do Enfermeiro",
  "5-13":"Abolição da Escravatura (1888)",
  "5-14":"Dia Continental do Seguro",
  "5-15":"Dia Internacional das Famílias",
  "5-16":"Dia Internacional da Luz",
  "5-17":"Dia da Constituição",
  "5-18":"Dia dos Vidreiros",
  "5-19":"Dia dos Acadêmicos do Direito",
  "5-20":"Dia Mundial da Abelha",
  "5-21":"Dia Mundial da Diversidade Cultural",
  "5-22":"Dia do Apicultor",
  "5-23":"Dia da Juventude Constitucionalista",
  "5-24":"Dia da Infantaria",
  "5-25":"Dia da Indústria",
  "5-26":"Dia Nacional do Bombeiro",
  "5-27":"Dia do Profissional Liberal",
  "5-28":"Dia Mundial do Hambúrguer",
  "5-29":"Dia do Estatístico",
  "5-30":"Dia das Bandeiras",
  "5-31":"Dia Mundial das Comunicações Sociais",
  "6-1":"Dia da Imprensa",
  "6-3":"Dia Mundial da Bicicleta",
  "6-4":"Corpus Christi",
  "6-5":"Dia da Ecologia",
  "6-6":"Dia de São Marcelino Champagnat",
  "6-7":"Dia Mundial da Segurança Alimentar",
  "6-8":"Dia Mundial dos Oceanos",
  "6-9":"Dia da Imunização",
  "6-10":"Dia da Artilharia",
  "6-11":"Dia da Marinha Brasileira",
  "6-12":"Dia Mundial Contra o Trabalho Infantil",
  "6-13":"Dia Mundial de Consciencialização do Albinismo",
  "6-14":"Dia Mundial do Doador de Sangue",
  "6-15":"Dia do Paleontólogo",
  "6-16":"Dia da Criança Africana",
  "6-17":"Dia Mundial de Combate à Desertificação e à Seca",
  "6-18":"Dia do Químico",
  "6-19":"Dia do Cinema Brasileiro",
  "6-20":"Dia Mundial do Refugiado",
  "6-21":"Dia Internacional do Yoga",
  "6-22":"Dia do Aeroviário",
  "6-24":"Dia de São João",
  "6-25":"Dia Mundial do Marinheiro",
  "6-26":"Dia Internacional contra o Abuso e Tráfico Ilícito de Drogas",
  "6-27":"Dia das Micro, Pequenas e Médias Empresas",
  "6-28":"Dia Internacional do Orgulho LGBTQIAPN+",
  "6-29":"Dia de São Pedro e São Paulo",
  "6-30":"Dia do Caminhoneiro",
  "7-1":"Dia da vacina BCG",
  "7-2":"Dia da Independência da Bahia",
  "7-3":"Dia Internacional das Cooperativas",
  "7-4":"Independência dos EUA (1776)",
  "7-5":"Dia da Fundação do Exército da Salvação",
  "7-6":"Dia da Criação do IBGE",
  "7-7":"Dia Mundial do Chocolate",
  "7-8":"Dia do Panificador",
  "7-9":"Dia da Revolução e do Soldado Constitucionalista",
  "7-10":"Dia da Pizza",
  "7-11":"Dia Mundial da População",
  "7-12":"Dia do Engenheiro Florestal",
  "7-13":"Dia do Cantor",
  "7-14":"Dia da Liberdade de Pensamento",
  "7-15":"Dia Nacional dos Clubes",
  "7-16":"Dia do Comerciante",
  "7-17":"Dia de Proteção às Florestas",
  "7-18":"Dia Internacional de Nelson Mandela",
  "7-19":"Dia da Caridade",
  "7-20":"Dia do Amigo e Internacional da Amizade",
  "7-21":"Dia dos Mortos da Marinha",
  "7-22":"Dia do Cantor Lírico",
  "7-23":"Dia do Guarda Rodoviário",
  "7-25":"Dia de São Cristóvão",
  "7-26":"Dia dos Avós",
  "7-27":"Dia do Motociclista",
  "7-28":"Dia do Agricultor",
  "7-29":"Dia da Identificação",
  "7-30":"Dia Mundial contra o Tráfico de Pessoas",
  "7-31":"Dia da Campanha do Quilo",
  "8-1":"Dia Nacional do Selo",
  "8-2":"Início da Semana da Cultura Nordestina",
  "8-3":"Dia do Capoeirista",
  "8-4":"Dia da Campanha Educativa de Combate ao Câncer",
  "8-5":"Dia Nacional da Saúde",
  "8-6":"Dia Nacional dos Profissionais da Educação",
  "8-7":"Dia Nacional do Documentário Brasileiro",
  "8-8":"Dia do Pároco",
  "8-9":"Dia dos Pais (algumas regiões)",
  "8-10":"Dia da Solidariedade Cristã",
  "8-11":"Dia da Televisão",
  "8-12":"Dia Internacional da Juventude",
  "8-13":"Dia do Economista",
  "8-14":"Dia do Cardiologista",
  "8-15":"Assunção de Nossa Senhora",
  "8-16":"Dia do Filósofo",
  "8-17":"Dia do Patrimônio Histórico Nacional",
  "8-18":"Dia do Estagiário",
  "8-19":"Dia Mundial Humanitário",
  "8-20":"Dia dos Maçons",
  "8-21":"Dia Internacional de Lembrança às Vítimas do Terrorismo",
  "8-22":"Dia do Folclore",
  "8-23":"Dia Internacional em Memória do Tráfico de Escravos",
  "8-24":"Dia da Infância",
  "8-25":"Dia do Feirante",
  "8-26":"Dia Internacional da Igualdade da Mulher",
  "8-27":"Dia do Corretor de Imóveis",
  "8-28":"Dia da Avicultura",
  "8-29":"Dia Internacional contra Testes Nucleares",
  "8-30":"Dia Internacional das Vítimas de Desaparecimentos Forçados",
  "8-31":"Dia da Nutricionista",
  "9-1":"Início da Semana da Pátria",
  "9-2":"Dia do Repórter Fotográfico",
  "9-3":"Dia do Biólogo",
  "9-4":"Dia da Lei Eusébio de Queirós",
  "9-5":"Dia Internacional da Caridade",
  "9-6":"Dia do Alfaiate",
  "9-7":"Independência do Brasil (1822)",
  "9-8":"Dia Internacional da Alfabetização",
  "9-9":"Dia do Administrador",
  "9-10":"Dia Mundial de Prevenção do Suicídio",
  "9-11":"Sancionada Lei de Defesa do Direito do Consumidor (1990)",
  "9-12":"Dia do Operador de Rastreamento",
  "9-13":"Dia do Programador",
  "9-14":"Dia da Cruz",
  "9-15":"Dia do Cliente",
  "9-16":"Dia Internacional para a Preservação da Camada de Ozônio",
  "9-17":"Dia da Compreensão Mundial",
  "9-18":"Dia dos Símbolos Nacionais",
  "9-19":"Dia de São Geraldo",
  "9-20":"Dia do Baterista",
  "9-21":"Dia Internacional da Paz",
  "9-22":"Início da Primavera",
  "9-23":"Dia Mundial das Línguas Gestuais",
  "9-24":"Dia do Mototaxista",
  "9-25":"Dia Nacional do Rádio",
  "9-26":"Dia Mundial do Mar",
  "9-27":"Dia de Cosme e Damião",
  "9-28":"Dia Internacional do Acesso Universal à Informação",
  "9-29":"Dia do Anunciante",
  "9-30":"Dia da Secretária",
  "10-1":"Dia de Santa Terezinha",
  "10-2":"Dia do Anjo da Guarda",
  "10-3":"Dia do Petróleo Brasileiro",
  "10-4":"Dia da Natureza",
  "10-5":"Dia Mundial dos Professores",
  "10-6":"Dia do Prefeito",
  "10-7":"Dia Mundial do Habitat",
  "10-8":"Dia do Nordestino",
  "10-9":"Dia Mundial dos Correios",
  "10-10":"Dia Mundial da Saúde Mental",
  "10-11":"Dia do Deficiente Físico",
  "10-12":"Dia de Nossa Senhora Aparecida",
  "10-13":"Dia do Fisioterapeuta",
  "10-14":"Dia Nacional da Pecuária",
  "10-15":"Dia Internacional da Mulher Rural",
  "10-16":"Dia da Ciência e Tecnologia",
  "10-17":"Dia da Valorização do Queijo de Leite Cru",
  "10-18":"Dia do Estivador",
  "10-19":"Dia do Profissional da Informática",
  "10-20":"Dia Internacional do Bicho Preguiça",
  "10-21":"Dia do Contato",
  "10-22":"Dia Internacional da Consciência da Gagueira",
  "10-23":"Dia da Força Aérea Brasileira",
  "10-24":"Dia Internacional do Bucho",
  "10-25":"Dia Internacional das Artistas",
  "10-26":"Dia da Cruz Vermelha",
  "10-27":"Dia Mundial do Patrimônio Audiovisual",
  "10-28":"Dia de São Judas Tadeu",
  "10-29":"Dia do Cerimonialista",
  "10-30":"Dia do Balconista",
  "10-31":"Dia Mundial das Cidades",
  "11-1":"Dia Mundial do Veganismo",
  "11-2":"Dia de Finados",
  "11-3":"Dia do Cabeleireiro",
  "11-4":"Dia do Inventor",
  "11-5":"Dia da Ciência e Cultura",
  "11-6":"Dia Nacional do Riso",
  "11-7":"Dia do Radialista",
  "11-8":"Dia do Radiologista",
  "11-9":"Dia Mundial da Liberdade",
  "11-10":"Dia do Trigo",
  "11-12":"Dia do Diretor de Escola",
  "11-13":"Dia Mundial da Gentileza",
  "11-14":"Dia Mundial do Combate à Diabetes",
  "11-15":"Proclamação da República (1889)",
  "11-16":"Semana da Música",
  "11-17":"Dia da Criatividade",
  "11-18":"Dia do Conselheiro Tutelar",
  "11-19":"Dia Mundial do Toalete",
  "11-20":"Dia do Auditor Interno",
  "11-21":"Dia Mundial da Filosofia",
  "11-22":"Dia do Músico",
  "11-23":"Dia do Engenheiro Eletricista",
  "11-24":"Dia do Quadro Auxiliar de Oficiais",
  "11-25":"Dia Nacional do Doador de Sangue",
  "11-26":"Dia Interamericano do Ministério Público",
  "11-27":"Dia do Técnico da Segurança do Trabalho",
  "11-28":"Dia do Soldado Desconhecido",
  "11-29":"Dia Nacional da Onça-Pintada",
  "11-30":"Dia da Amizade Brasil-Argentina",
  "12-1":"Dia do Numismata",
  "12-2":"Dia Internacional para a Abolição da Escravatura",
  "12-3":"Dia Internacional do Portador de Deficiência",
  "12-4":"Dia da Propaganda",
  "12-5":"Dia Internacional dos Voluntários",
  "12-6":"Dia do Neuropsicopedagogo",
  "12-7":"Dia do Médico Cirurgião Plástico",
  "12-8":"Dia da Família",
  "12-9":"Dia Internacional contra a Corrupção",
  "12-10":"Declaração Universal dos Direitos Humanos",
  "12-11":"Dia do Engenheiro",
  "12-12":"Dia Mundial da Cobertura Universal de Saúde",
  "12-13":"Dia Mundial da Iluminação por Velas",
  "12-14":"Dia Nacional do Ministério Público",
  "12-15":"Dia do Arquiteto",
  "12-16":"Dia do Reservista",
  "12-17":"Dia do Pastor Presbiteriano",
  "12-18":"Dia Internacional dos Migrantes",
  "12-19":"Dia Estadual da Poesia (MT)",
  "12-20":"Dia do Mecânico",
  "12-21":"Início do Verão",
  "12-23":"Dia do Vizinho",
  "12-24":"Dia do Órfão",
  "12-25":"Natal",
  "12-26":"Dia da Lembrança",
  "12-27":"Criado o Departamento de Imprensa e Propaganda (1939)",
  "12-28":"Dia do Salva-vidas",
  "12-30":"Criação do Vale do Aço (1998)",
  "12-31":"Réveillon"
};
