// Curiosidade/data comemorativa do dia, exibida na tela de Métricas
// Executivas abaixo do calendário (pedido do usuário, 2026-09-18). Lista
// curada manualmente (365 entradas, uma por dia do ano, chave 'M-D' sem
// zero à esquerda) em vez de API pública de datas comemorativas — decisão
// registrada na conversa: controle de qualidade e curadoria de relevância
// pro negócio (comida/bebida/consumo) importam mais aqui do que cobertura
// automática, e uma API externa é mais um ponto de falha sem necessidade.
// Quando o dia tem mais de um evento (múltiplas frases na fonte original,
// separadas por " / "), mostra só o primeiro, pra manter o texto curto e
// discreto. Dias sem evento cadastrado na fonte original (marcados como
// "(sem data especial registrada)") ficam de fora do objeto — o dashboard
// simplesmente não mostra a linha nesses dias.
const DATAS_COMEMORATIVAS = {
  "1-1":"Confraternização Universal",
  "1-2":"Dia Mundial Dos Introvertidos",
  "1-3":"Dia Do Juiz De Menores",
  "1-4":"Dia Da Abreugrafia",
  "1-5":"Criação Da 1ª Tipografia No Brasil",
  "1-6":"Dia Da Gratidão",
  "1-7":"Dia Da Liberdade De Cultos",
  "1-8":"Dia Do Fotógrafo",
  "1-9":"Dia Do Astronauta",
  "1-10":"Festa De São Gonçalo Do Amarante",
  "1-11":"Dia Do Controle Da Poluição Por Agrotóxicos",
  "1-12":"Dia Do Empresário Contábil",
  "1-13":"Dia Internacional Do Leonismo",
  "1-14":"Dia Internacional Da Pipa",
  "1-15":"Dia Dos Adultos",
  "1-16":"Dia Dos Cortadores De Cana-De-Açúcar",
  "1-17":"Dia Dos Tribunais De Contas Do Brasil",
  "1-18":"Dia De Santo Irmão Jaime Hilário",
  "1-19":"Dia Internacional Do Queijo Quark",
  "1-20":"Dia Do Farmacêutico",
  "1-21":"Dia Internacional Do Moletom",
  "1-22":"Dia De Santo André",
  "1-23":"Dia Internacional Da Medicina Integrativa",
  "1-24":"Dia Internacional Da Educação",
  "1-25":"Dia Do Carteiro",
  "1-26":"Dia Da Gula",
  "1-27":"Dia Internacional Em Memória Às Vítimas Do Holocausto",
  "1-28":"Dia Internacional Da Privacidade De Dados",
  "1-29":"Dia Internacional Do Hanseniano",
  "1-30":"Dia Da Saudade",
  "1-31":"Dia Do Lançamento Do 1º Satélite (EUA)",
  "2-1":"Dia Do Publicitário",
  "2-2":"Dia De Iemanjá",
  "2-3":"Dia Da Navegação No Rio São Francisco",
  "2-4":"Criação Do Facebook (2004)",
  "2-5":"Dia Do Datiloscopista",
  "2-6":"Dia Internacional Da Tolerância Zero À Mutilação Vaginal",
  "2-7":"Dia Do Gráfico",
  "2-8":"Dia Do Quadro Do Magistério Do Exército",
  "2-10":"Dia Mundial Das Leguminosas",
  "2-11":"Dia Internacional Das Mulheres E Meninas Na Ciência",
  "2-12":"Dia De Darwin",
  "2-13":"Dia Mundial Do Rádio",
  "2-14":"Dia Internacional Da Doação De Livros",
  "2-15":"Dia Internacional De Luta Contra O Câncer Na Infância",
  "2-16":"Dia Do Repórter",
  "2-17":"Carnaval",
  "2-18":"Quarta-Feira De Cinzas",
  "2-19":"Dia Do Esportista",
  "2-20":"Dia Mundial Da Justiça Social",
  "2-21":"Dia Internacional Da Baleia",
  "2-22":"Dia Do Auxiliar De Serviços Gerais",
  "2-23":"Dia Do Rotaryano",
  "2-24":"Promulgação Da 1ª Constituição Republicana (1891)",
  "2-25":"Dia Da Criação Do Ministério Das Comunicações",
  "2-26":"Dia Do Comediante",
  "2-27":"Dia Do Agente Fiscal Da Receita Federal",
  "2-28":"Dia Da Ressaca",
  "3-1":"Dia Da Discriminação Zero",
  "3-2":"Dia Da Oração",
  "3-3":"Dia Mundial Da Vida Selvagem",
  "3-4":"Dia Mundial Da Oração",
  "3-5":"Dia Do Filatelista Brasileiro",
  "3-6":"Dia Internacional Do Optometrista",
  "3-7":"Dia Dos Fuzileiros Navais",
  "3-8":"Dia Internacional Da Mulher",
  "3-9":"Dia Internacional Do DJ",
  "3-10":"Dia Internacional Da Gaita De Foles",
  "3-11":"Dia Internacional Do Encanamento",
  "3-12":"Dia Internacional Da Pochete",
  "3-13":"Dia Do Conservacionismo",
  "3-14":"Dia Do Vendedor De Livros",
  "3-15":"Dia Mundial Do Consumidor",
  "3-16":"Dia Nacional De Conscientização Sobre As Mudanças Climáticas",
  "3-18":"Dia Nacional Da Imigração Judaica",
  "3-19":"Dia De São José",
  "3-20":"Dia Internacional Da Felicidade",
  "3-21":"Dia Mundial Da Poesia",
  "3-22":"Dia Mundial Da Água",
  "3-23":"Dia Mundial Da Meteorologia",
  "3-24":"Dia Mundial Da Tuberculose",
  "3-25":"Dia Nacional Do Oficial De Justiça",
  "3-26":"Dia Do Cacau",
  "3-27":"Dia Do Circo",
  "3-28":"Dia Do Diagramador",
  "3-29":"1º Voo De Balão Dirigível No Rio (1882)",
  "3-30":"Dia Mundial Da Juventude",
  "3-31":"Dia Da Integração Nacional",
  "4-1":"Dia Da Mentira",
  "4-2":"Dia Do Propagandista",
  "4-3":"Dia Do Atuário",
  "4-4":"Dia Nacional Do Parkinsoniano",
  "4-5":"Dia Das Telecomunicações",
  "4-6":"Dia Nacional De Mobilização Pela Saúde E Qualidade De Vida",
  "4-7":"Dia Do Corretor",
  "4-8":"Dia Da Natação",
  "4-9":"Dia Nacional Do Aço",
  "4-10":"Dia Da Engenharia",
  "4-11":"Dia Do Infectologista",
  "4-12":"Dia Do Obstetra",
  "4-13":"1ª Execução Do Hino Nacional (1831)",
  "4-14":"Dia Pan-Americano",
  "4-15":"Dia Da Conservação Do Solo",
  "4-16":"Dia Da Voz",
  "4-17":"Dia Do Lojista De CD",
  "4-18":"Dia De Monteiro Lobato",
  "4-19":"Dia Do Exército Brasileiro",
  "4-20":"Dia Do Diplomata",
  "4-21":"Tiradentes",
  "4-22":"Descobrimento Do Brasil (1500)",
  "4-23":"Dia De São Jorge",
  "4-24":"Dia Do Agente De Viagem",
  "4-25":"Dia Mundial Da Malária",
  "4-26":"Dia Mundial Da Propriedade Intelectual",
  "4-27":"Dia Da Empregada Doméstica",
  "4-28":"Dia Mundial Da Segurança E Saúde No Trabalho",
  "4-29":"Dia Internacional Da Dança",
  "4-30":"Dia Internacional Do Jazz",
  "5-1":"Dia Mundial Do Trabalho",
  "5-2":"Dia Mundial Do Atum",
  "5-3":"Dia Mundial Da Liberdade De Imprensa",
  "5-4":"Dia Do Calculista Estrutural",
  "5-5":"Dia Do Artista Pintor",
  "5-6":"Dia Do Cartógrafo",
  "5-7":"Dia Do Oftalmologista",
  "5-8":"Dia Do Profissional De Marketing",
  "5-9":"Dia Da Europa",
  "5-10":"Dia Das Mães",
  "5-11":"Dia Mundial Das Aves Migratórias",
  "5-12":"Dia Mundial Do Enfermeiro",
  "5-13":"Abolição Da Escravatura (1888)",
  "5-14":"Dia Continental Do Seguro",
  "5-15":"Dia Internacional Das Famílias",
  "5-16":"Dia Internacional Da Luz",
  "5-17":"Dia Da Constituição",
  "5-18":"Dia Dos Vidreiros",
  "5-19":"Dia Dos Acadêmicos Do Direito",
  "5-20":"Dia Mundial Da Abelha",
  "5-21":"Dia Mundial Da Diversidade Cultural",
  "5-22":"Dia Do Apicultor",
  "5-23":"Dia Da Juventude Constitucionalista",
  "5-24":"Dia Da Infantaria",
  "5-25":"Dia Da Indústria",
  "5-26":"Dia Nacional Do Bombeiro",
  "5-27":"Dia Do Profissional Liberal",
  "5-28":"Dia Mundial Do Hambúrguer",
  "5-29":"Dia Do Estatístico",
  "5-30":"Dia Das Bandeiras",
  "5-31":"Dia Mundial Das Comunicações Sociais",
  "6-1":"Dia Da Imprensa",
  "6-3":"Dia Mundial Da Bicicleta",
  "6-4":"Corpus Christi",
  "6-5":"Dia Da Ecologia",
  "6-6":"Dia De São Marcelino Champagnat",
  "6-7":"Dia Mundial Da Segurança Alimentar",
  "6-8":"Dia Mundial Dos Oceanos",
  "6-9":"Dia Da Imunização",
  "6-10":"Dia Da Artilharia",
  "6-11":"Dia Da Marinha Brasileira",
  "6-12":"Dia Mundial Contra O Trabalho Infantil",
  "6-13":"Dia Mundial De Consciencialização Do Albinismo",
  "6-14":"Dia Mundial Do Doador De Sangue",
  "6-15":"Dia Do Paleontólogo",
  "6-16":"Dia Da Criança Africana",
  "6-17":"Dia Mundial De Combate À Desertificação E À Seca",
  "6-18":"Dia Do Químico",
  "6-19":"Dia Do Cinema Brasileiro",
  "6-20":"Dia Mundial Do Refugiado",
  "6-21":"Dia Internacional Do Yoga",
  "6-22":"Dia Do Aeroviário",
  "6-24":"Dia De São João",
  "6-25":"Dia Mundial Do Marinheiro",
  "6-26":"Dia Internacional Contra O Abuso E Tráfico Ilícito De Drogas",
  "6-27":"Dia Das Micro, Pequenas E Médias Empresas",
  "6-28":"Dia Internacional Do Orgulho LGBTQIAPN+",
  "6-29":"Dia De São Pedro E São Paulo",
  "6-30":"Dia Do Caminhoneiro",
  "7-1":"Dia Da Vacina BCG",
  "7-2":"Dia Da Independência Da Bahia",
  "7-3":"Dia Internacional Das Cooperativas",
  "7-4":"Independência Dos EUA (1776)",
  "7-5":"Dia Da Fundação Do Exército Da Salvação",
  "7-6":"Dia Da Criação Do IBGE",
  "7-7":"Dia Mundial Do Chocolate",
  "7-8":"Dia Do Panificador",
  "7-9":"Dia Da Revolução E Do Soldado Constitucionalista",
  "7-10":"Dia Da Pizza",
  "7-11":"Dia Mundial Da População",
  "7-12":"Dia Do Engenheiro Florestal",
  "7-13":"Dia Do Cantor",
  "7-14":"Dia Da Liberdade De Pensamento",
  "7-15":"Dia Nacional Dos Clubes",
  "7-16":"Dia Do Comerciante",
  "7-17":"Dia De Proteção Às Florestas",
  "7-18":"Dia Internacional De Nelson Mandela",
  "7-19":"Dia Da Caridade",
  "7-20":"Dia Do Amigo E Internacional Da Amizade",
  "7-21":"Dia Dos Mortos Da Marinha",
  "7-22":"Dia Do Cantor Lírico",
  "7-23":"Dia Do Guarda Rodoviário",
  "7-25":"Dia De São Cristóvão",
  "7-26":"Dia Dos Avós",
  "7-27":"Dia Do Motociclista",
  "7-28":"Dia Do Agricultor",
  "7-29":"Dia Da Identificação",
  "7-30":"Dia Mundial Contra O Tráfico De Pessoas",
  "7-31":"Dia Da Campanha Do Quilo",
  "8-1":"Dia Nacional Do Selo",
  "8-2":"Início Da Semana Da Cultura Nordestina",
  "8-3":"Dia Do Capoeirista",
  "8-4":"Dia Da Campanha Educativa De Combate Ao Câncer",
  "8-5":"Dia Nacional Da Saúde",
  "8-6":"Dia Nacional Dos Profissionais Da Educação",
  "8-7":"Dia Nacional Do Documentário Brasileiro",
  "8-8":"Dia Do Pároco",
  "8-9":"Dia Dos Pais (Algumas Regiões)",
  "8-10":"Dia Da Solidariedade Cristã",
  "8-11":"Dia Da Televisão",
  "8-12":"Dia Internacional Da Juventude",
  "8-13":"Dia Do Economista",
  "8-14":"Dia Do Cardiologista",
  "8-15":"Assunção De Nossa Senhora",
  "8-16":"Dia Do Filósofo",
  "8-17":"Dia Do Patrimônio Histórico Nacional",
  "8-18":"Dia Do Estagiário",
  "8-19":"Dia Mundial Humanitário",
  "8-20":"Dia Dos Maçons",
  "8-21":"Dia Internacional De Lembrança Às Vítimas Do Terrorismo",
  "8-22":"Dia Do Folclore",
  "8-23":"Dia Internacional Em Memória Do Tráfico De Escravos",
  "8-24":"Dia Da Infância",
  "8-25":"Dia Do Feirante",
  "8-26":"Dia Internacional Da Igualdade Da Mulher",
  "8-27":"Dia Do Corretor De Imóveis",
  "8-28":"Dia Da Avicultura",
  "8-29":"Dia Internacional Contra Testes Nucleares",
  "8-30":"Dia Internacional Das Vítimas De Desaparecimentos Forçados",
  "8-31":"Dia Da Nutricionista",
  "9-1":"Início Da Semana Da Pátria",
  "9-2":"Dia Do Repórter Fotográfico",
  "9-3":"Dia Do Biólogo",
  "9-4":"Dia Da Lei Eusébio De Queirós",
  "9-5":"Dia Internacional Da Caridade",
  "9-6":"Dia Do Alfaiate",
  "9-7":"Independência Do Brasil (1822)",
  "9-8":"Dia Internacional Da Alfabetização",
  "9-9":"Dia Do Administrador",
  "9-10":"Dia Mundial De Prevenção Do Suicídio",
  "9-11":"Sancionada Lei De Defesa Do Direito Do Consumidor (1990)",
  "9-12":"Dia Do Operador De Rastreamento",
  "9-13":"Dia Do Programador",
  "9-14":"Dia Da Cruz",
  "9-15":"Dia Do Cliente",
  "9-16":"Dia Internacional Para A Preservação Da Camada De Ozônio",
  "9-17":"Dia Da Compreensão Mundial",
  "9-18":"Dia Dos Símbolos Nacionais",
  "9-19":"Dia De São Geraldo",
  "9-20":"Dia Do Baterista",
  "9-21":"Dia Internacional Da Paz",
  "9-22":"Início Da Primavera",
  "9-23":"Dia Mundial Das Línguas Gestuais",
  "9-24":"Dia Do Mototaxista",
  "9-25":"Dia Nacional Do Rádio",
  "9-26":"Dia Mundial Do Mar",
  "9-27":"Dia De Cosme E Damião",
  "9-28":"Dia Internacional Do Acesso Universal À Informação",
  "9-29":"Dia Do Anunciante",
  "9-30":"Dia Da Secretária",
  "10-1":"Dia De Santa Terezinha",
  "10-2":"Dia Do Anjo Da Guarda",
  "10-3":"Dia Do Petróleo Brasileiro",
  "10-4":"Dia Da Natureza",
  "10-5":"Dia Mundial Dos Professores",
  "10-6":"Dia Do Prefeito",
  "10-7":"Dia Mundial Do Habitat",
  "10-8":"Dia Do Nordestino",
  "10-9":"Dia Mundial Dos Correios",
  "10-10":"Dia Mundial Da Saúde Mental",
  "10-11":"Dia Do Deficiente Físico",
  "10-12":"Dia De Nossa Senhora Aparecida",
  "10-13":"Dia Do Fisioterapeuta",
  "10-14":"Dia Nacional Da Pecuária",
  "10-15":"Dia Internacional Da Mulher Rural",
  "10-16":"Dia Da Ciência E Tecnologia",
  "10-17":"Dia Da Valorização Do Queijo De Leite Cru",
  "10-18":"Dia Do Estivador",
  "10-19":"Dia Do Profissional Da Informática",
  "10-20":"Dia Internacional Do Bicho Preguiça",
  "10-21":"Dia Do Contato",
  "10-22":"Dia Internacional Da Consciência Da Gagueira",
  "10-23":"Dia Da Força Aérea Brasileira",
  "10-24":"Dia Internacional Do Bucho",
  "10-25":"Dia Internacional Das Artistas",
  "10-26":"Dia Da Cruz Vermelha",
  "10-27":"Dia Mundial Do Patrimônio Audiovisual",
  "10-28":"Dia De São Judas Tadeu",
  "10-29":"Dia Do Cerimonialista",
  "10-30":"Dia Do Balconista",
  "10-31":"Dia Mundial Das Cidades",
  "11-1":"Dia Mundial Do Veganismo",
  "11-2":"Dia De Finados",
  "11-3":"Dia Do Cabeleireiro",
  "11-4":"Dia Do Inventor",
  "11-5":"Dia Da Ciência E Cultura",
  "11-6":"Dia Nacional Do Riso",
  "11-7":"Dia Do Radialista",
  "11-8":"Dia Do Radiologista",
  "11-9":"Dia Mundial Da Liberdade",
  "11-10":"Dia Do Trigo",
  "11-12":"Dia Do Diretor De Escola",
  "11-13":"Dia Mundial Da Gentileza",
  "11-14":"Dia Mundial Do Combate À Diabetes",
  "11-15":"Proclamação Da República (1889)",
  "11-16":"Semana Da Música",
  "11-17":"Dia Da Criatividade",
  "11-18":"Dia Do Conselheiro Tutelar",
  "11-19":"Dia Mundial Do Toalete",
  "11-20":"Dia Do Auditor Interno",
  "11-21":"Dia Mundial Da Filosofia",
  "11-22":"Dia Do Músico",
  "11-23":"Dia Do Engenheiro Eletricista",
  "11-24":"Dia Do Quadro Auxiliar De Oficiais",
  "11-25":"Dia Nacional Do Doador De Sangue",
  "11-26":"Dia Interamericano Do Ministério Público",
  "11-27":"Dia Do Técnico Da Segurança Do Trabalho",
  "11-28":"Dia Do Soldado Desconhecido",
  "11-29":"Dia Nacional Da Onça-Pintada",
  "11-30":"Dia Da Amizade Brasil-Argentina",
  "12-1":"Dia Do Numismata",
  "12-2":"Dia Internacional Para A Abolição Da Escravatura",
  "12-3":"Dia Internacional Do Portador De Deficiência",
  "12-4":"Dia Da Propaganda",
  "12-5":"Dia Internacional Dos Voluntários",
  "12-6":"Dia Do Neuropsicopedagogo",
  "12-7":"Dia Do Médico Cirurgião Plástico",
  "12-8":"Dia Da Família",
  "12-9":"Dia Internacional Contra A Corrupção",
  "12-10":"Declaração Universal Dos Direitos Humanos",
  "12-11":"Dia Do Engenheiro",
  "12-12":"Dia Mundial Da Cobertura Universal De Saúde",
  "12-13":"Dia Mundial Da Iluminação Por Velas",
  "12-14":"Dia Nacional Do Ministério Público",
  "12-15":"Dia Do Arquiteto",
  "12-16":"Dia Do Reservista",
  "12-17":"Dia Do Pastor Presbiteriano",
  "12-18":"Dia Internacional Dos Migrantes",
  "12-19":"Dia Estadual Da Poesia (MT)",
  "12-20":"Dia Do Mecânico",
  "12-21":"Início Do Verão",
  "12-23":"Dia Do Vizinho",
  "12-24":"Dia Do Órfão",
  "12-25":"Natal",
  "12-26":"Dia Da Lembrança",
  "12-27":"Criado O Departamento De Imprensa E Propaganda (1939)",
  "12-28":"Dia Do Salva-Vidas",
  "12-30":"Criação Do Vale Do Aço (1998)",
  "12-31":"Réveillon"
};
